[project]
name = "renux"
version = "0.4.0"
description = "A terminal-based bulk file renamer with a TUI"
authors = [
    {name = "Andrian Lloyd Maagma", email = "maagmaandrian@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.10,<4.0.0"
keywords = ["rename", "bulk-rename", "cli", "tui", "files", "regex"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Terminals",
    "Topic :: Utilities",
]
dependencies = [
    "python-slugify (>=8.0.4,<9.0.0)",
    "rich (>=14.0.0,<15.0.0)",
    "textual (>=3.3.0,<4.0.0)",
    "pillow (>=11.0.0,<12.0.0)",
    "hachoir (>=3.3.0,<4.0.0)",
    "typer (>=0.27.1,<0.28.0)",
]

[project.urls]
Homepage = "https://github.com/andrianllmm/renux"
Repository = "https://github.com/andrianllmm/renux"
Issues = "https://github.com/andrianllmm/renux/issues"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
renux = "renux.cli:main"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.3"

[tool.poetry.group.dev.dependencies]
mypy = "^1.16.1"
commitizen = "^4.8.3"
black = "^26.3.1"
pre-commit = "^4.2.0"
isort = "^6.0.1"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "semver2"
version_provider = "pep621"

[tool.isort]
profile = "black"

[[tool.mypy.overrides]]
module = "hachoir.*"
ignore_missing_imports = true
