"""Regenerate the README.

- Keeps the README in sync with the tags registry (`src/renux/tags.py`).
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from renux.tags_reference import render_readme  # noqa: E402

README_PATH = Path(__file__).resolve().parent.parent / "README.md"

START_MARKER = "<!-- TAGS:START (auto-generated by scripts/sync_readme.py, do not edit by hand) -->"
END_MARKER = "<!-- TAGS:END -->"


def main() -> int:
    content = README_PATH.read_text()

    pattern = re.compile(
        rf"{re.escape(START_MARKER)}\n.*?\n{re.escape(END_MARKER)}", re.DOTALL
    )
    if not pattern.search(content):
        raise SystemExit(
            f"README.md is missing the {START_MARKER!r} / {END_MARKER!r} markers."
        )

    new_block = f"{START_MARKER}\n{render_readme()}\n{END_MARKER}"
    new_content = pattern.sub(new_block, content)

    if new_content == content:
        return 0

    README_PATH.write_text(new_content)
    print("README.md tags reference updated.")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
