name: Publish to PyPI

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Manual Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install -U pip poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install --only main --no-interaction

      - name: Build package
        run: |
          poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
