name: Release to TestPyPI

on:
  push:
    tags:
      - "v*.*.*-*"

jobs:
  release-testpypi:
    name: Build and Publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install -U pip poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install --only main --no-interaction

      - name: Build package
        run: |
          poetry build

      - name: Configure TestPyPI Repository
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi $POETRY_PYPI_TOKEN_TESTPYPI
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_TOKEN }}

      - name: Publish to TestPyPI
        run: |
          poetry publish -r testpypi --no-interaction
