name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release-pypi:
    name: Manual Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install -U pip poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install --only main --no-interaction

      - name: Build package
        run: |
          poetry build

      - name: Configure PyPI Repository
        run: |
          poetry config pypi-token.pypi $POETRY_PYPI_TOKEN_PYPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}

      - name: Publish to PyPI
        run: |
          poetry publish --no-interaction
