name: Release to TestPyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  testpypi-release:
    name: Build and Publish to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install -U pip poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install --only main --no-interaction

      - name: Build package
        run: |
          poetry build

      - name: Publish to TestPyPI
        env:
          POETRY_PYPI_TOKEN_TESTPYPI: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry publish -r testpypi --username __token__ --password $POETRY_PYPI_TOKEN_TESTPYPI
